# before_install:
  # - openssl aes-256-cbc -K $encrypted_9ec4e4461a7a_key -iv $encrypted_9ec4e4461a7a_iv -in config.php.enc -out config.php -d
# install: false
language: php
script: phpunit test.php
# after_success:
#   - eval "$(ssh-agent -s)" #start the ssh agent
#   - chmod 600 .travis/deploy_key.pem # this key should have push access
#   - ssh-add .travis/deploy_key.pem
#   - git remote add deploy DEPLOY_REPO_URI_GOES_HERE
#   - git push deploy