before_install:
  - openssl aes-256-cbc -K $encrypted_9ec4e4461a7a_key -iv $encrypted_9ec4e4461a7a_iv -in config.php.enc -out config.php -d
install: true
language: php
script: phpunit Test.php
after_success:
  - "curl -T index.php -u $FTP_USER:$FTP_PASSWORD ftp://ftp087889.bytenet.nl/dev.ovfietsradar.nl/"
  - "curl -T config.php -u $FTP_USER:$FTP_PASSWORD ftp://ftp087889.bytenet.nl/dev.ovfietsradar.nl/"